# Generated by Django 5.0.6 on 2024-05-18 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_actor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='Director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director', to='movie_actor_app.director'),
        ),
    ]
